//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRight
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFunctions
    {
        public string Menu { get; set; }
        public string Applications { get; set; }
        public string Descriptions { get; set; }
        public string ParentMenu { get; set; }
    }
}
