//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRight
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFunctions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFunctions()
        {
            this.tblUserFunctions = new HashSet<tblUserFunctions>();
        }
    
        public string Menu { get; set; }
        public string Applications { get; set; }
        public string Descriptions { get; set; }
        public string ParentMenu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserFunctions> tblUserFunctions { get; set; }
    }
}
